Repository owncloud/android-library, pull requests merged in 2020-01, with the labels that each got.

#291 Finish remove Android 4.4 support
  sample_client/build.gradle
Labels: Sprint, approved by qa, code approved

#293 Replace Log_OC with timber
  owncloudComLibrary/build.gradle
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/DynamicSessionManager.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/OwnCloudClient.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/OwnCloudClientFactory.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/SimpleFactoryManager.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/SingleSessionManager.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/accounts/AccountUtils.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/authentication/oauth/OAuth2QueryParser.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/authentication/oauth/OAuth2RefreshAccessTokenOperation.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/authentication/oauth/OwnCloudOAuth2Provider.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/HttpClient.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/network/AdvancedX509TrustManager.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/network/ChunkFromFileRequestBody.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/network/NetworkUtils.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/network/ServerNameIndicator.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/network/WriteTimeoutEnforcer.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/operations/RemoteOperation.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/operations/RemoteOperationResult.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/utils/Log_OC.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/utils/LoggingHelper.kt
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/CreateRemoteFolderOperation.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/DownloadRemoteFileOperation.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/ExistenceCheckRemoteOperation.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/FileUtils.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/ReadRemoteFileOperation.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/ReadRemoteFolderOperation.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/RemoveRemoteFileOperation.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/RenameRemoteFileOperation.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/UploadRemoteFileOperation.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/chunks/ChunkedUploadRemoteFileOperation.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/CreateRemoteShareOperation.kt
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/GetRemoteShareOperation.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/GetRemoteShareesOperation.kt
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/GetRemoteSharesForFileOperation.kt
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/RemoveRemoteShareOperation.kt
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/ShareToRemoteOperationResultParser.kt
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/ShareXMLParser.kt
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/UpdateRemoteShareOperation.kt
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/GetRemoteCapabilitiesOperation.kt
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/GetRemoteStatusOperation.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/users/GetRemoteUserAvatarOperation.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/users/GetRemoteUserInfoOperation.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/users/GetRemoteUserQuotaOperation.java
Labels: code approved

#286 End of support for <10 servers
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/DynamicSessionManager.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/OwnCloudClient.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/OwnCloudClientManagerFactory.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/accounts/AccountUtils.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/authentication/OwnCloudCredentialsFactory.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/operations/RemoteOperationResult.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/CopyRemoteFileOperation.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/CreateRemoteFolderOperation.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/FileUtils.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/MoveRemoteFileOperation.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/RenameRemoteFileOperation.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/RemoteShare.kt
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/ShareToRemoteOperationResultParser.kt
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/ShareUtils.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/status/OwnCloudVersion.kt
Labels: code approved

#297 Build sample app successful
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/accounts/AccountUtils.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/authentication/OwnCloudBasicCredentials.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/authentication/oauth/OAuth2QueryParser.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/network/AdvancedX509TrustManager.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/network/FileRequestBody.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/CopyRemoteFileOperation.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/MoveRemoteFileOperation.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/files/ReadRemoteFileOperation.java
  owncloudComLibrary/src/main/java/com/owncloud/android/lib/resources/shares/ShareXMLParser.kt
  pom.xml
  sample_client/src/main/java/com/owncloud/android/lib/sampleclient/MainActivity.java
Labels: Estimation - 2 (S), Sprint, approved by qa, code approved
